---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5df1a4bf6f04a1ed3a643167b38d502575e29aef
    hooks:
      # General Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
        exclude: "\\.(svg|drawio)$"
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      # Python
      - id: debug-statements
  # Python: Syntax and Quotes
  - repo: https://gitlab.com/pycqa/flake8
    rev: bb61b3df82a938f7cd1ca32daab4a31e4586b281
    hooks:
      - id: flake8
        args:
          - --isolated
          - --inline-quotes=single
          - --max-line-length=100
        additional_dependencies: [flake8-quotes]
  # Python: isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args:
          - --project
          - cachet_netbox_sync
          - --case-sensitive
          - --section-default
          - THIRDPARTY
          - --force-grid-wrap
          - "0"
          - --force-single-line-imports
          - --trailing-comma
          - --line-width
          - "100"
          - --multi-line
          - "3"
          - --dont-order-by-type
          - --use-parentheses
  # Python: pycodestyle
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        args:
          - --in-place
          - --max-line-length
          - "100"
  # Requirements
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.3
    hooks:
      - id: python-safety-dependencies-check
