[bumpver]
current_version = "2022.02.08"
version_pattern = "YYYY.0M.0D[.PATCH]"
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"Dockerfile" = [
    "ENV IMAGE_VERSION={version}",
]
